# .github/workflows/answer.yml
name: Daily Answer Script

on:
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch:
    inputs:
      account:
        description: "账号"
        required: false
      password:
        description: "密码"
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      ACCOUNT: ${{ github.event.inputs.account || secrets.ACCOUNT }}
      PASSWORD: ${{ github.event.inputs.password || secrets.PASSWORD }}
      KEY: ${{ secrets.KEY }}
      IV: ${{ secrets.IV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Answer Script
        run: bun run index.ts

      - name: Send message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text="$ACCOUNT 答题成功"
